sudo: required
services:
  - docker


before_install:
  - docker build -t myersultan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run myersultan/react-test npm test -- --coverage

after_success:
  - docker build -t myersultan/multi-client ./client
  - docker build -t myersultan/multi-nginx ./nginx
  - docker build -t myersultan/multi-server ./server
  - docker build -t myersultan/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push myersultan/multi-client
  - docker push myersultan/multi-nginx
  - docker push myersultan/multi-server
  - docker push myersultan/multi-worker